### ISSUE TITLE
Make the repository public

### ISSUE THREAD

**Issue by ranocha** [SKopecz/PositiveIntegrators.jl#3]
Here are some things we should keep in mind when making the repo public:

- [x] Make the repo public
- [x] Add some badges to the README.md file (#5)
- [x] Integrate with Coverage report repos and activate the corresponding part in `.github/workflows/CI.yml` (#8)
- [x] Set up Documenter.jl (including the GItHub secret etc.) (#6)
- [x] Register it in the long run (https://github.com/JuliaRegistries/General/pull/103552)
- [ ] Update installation instructions in the README.md and the docs (#53)
